### ISSUE TITLE
luci-theme-rosy: Network/Switch view does not fit the screen

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#2645]
Built from master yesterday and using the latest Firefox on MacOs. A half of the view does not fit and there is no horizontal scroll bar.

<img width="1157" alt="Rosy-Switch" src="https://user-images.githubusercontent.com/5624569/55280285-ba73db00-52f9-11e9-976f-69cc81a77f6f.png">

ping @rosysong

**Comment by rosysong** [comment]
@fantom-x  
Fixed, please try below PR, thanks!
https://github.com/openwrt/luci/pull/2663

**Comment by fantom-x** [comment]
@rosysong I just compiled OpenWRT master @ 9385ff654e and the issue is still present.

**Comment by rosysong** [comment]
Will updated it later, this issue seems occur on routers with 5 ports.

**Comment by fantom-x** [comment]
Any luck?

**Comment by rosysong** [comment]
@fantom-x  Please wait patiently, thanks!

**Comment by fantom-x** [comment]
Thx for the fix, the table can now be scrolled horizontally. But it is still somewhat inconvenient to use: is it possible to shrink the table so that it is possible to see the entire table at once?
