### ISSUE TITLE
luci-theme-material: missing panel title in with client-side view

### ISSUE THREAD

**Issue by ysc3839** [openwrt/luci#3149]
When using client-side view, panel title is missing:
![image](https://user-images.githubusercontent.com/12028138/66372494-b3c8cd80-e9d8-11e9-821a-b9c11cf6c49c.png)
Server-side view is normal:
![image](https://user-images.githubusercontent.com/12028138/66372521-c4794380-e9d8-11e9-8fc7-e24ea42af77a.png)

I think it's because the code that creates it excutes on load, but the view is not loaded at that time.
https://github.com/openwrt/luci/blob/e459683822925bcdeb552673a4811aa3b4322640/themes/luci-theme-material/htdocs/luci-static/material/js/script.js#L174-L180

**Comment by jow-** [comment]
Yet another material theme specific bug.

**Comment by jow-** [comment]
Fixed as side-effect of 92eecedc8a52b0ba814daddb5167449a2ebb7f26

**Comment by ysc3839** [comment]
This issue still not fixed.
![image](https://user-images.githubusercontent.com/12028138/72665398-181d1380-3a43-11ea-8e73-96fcdc895b18.png)

Version is LuCI (git-20.016.76613-0608ff0) / OpenWrt SNAPSHOT r12034-1322190fd3.

Activate a breakpoint in script.js, at this time `legend` elements is not loaded.
![image](https://user-images.githubusercontent.com/12028138/72665448-9aa5d300-3a43-11ea-99fd-a4bc737237b2.png)

**Comment by jow-** [comment]
Okay, someone who cares about material needs to look into this then.

**Comment by solidus1983** [comment]
there is quite a few bugs in the Material theme, however it only shows in master (19.07 rc2 branch is fine). So yes it would be down to the latest changes made.

I was looking into it for my theme which is based on Material however my only system decided to take a dump of death.

**Comment by oldium** [comment]
I am on current master branch and can confirm this is still there. The trigger `luci-loaded` is executed when actually no `legend` element exists yet. The GUI is created asynchronously, so the conversion from `legend` to `span` needs to take place some time later. Any chance to get this fixed?

**Comment by oldium** [comment]
The `View` class will most probably need to emit a notification when the DOM is ready - in `luci.js` in constructor of `View` class:

https://github.com/openwrt/luci/blob/0d0816ca107c84631ab03b5ef2e6d373e102d09a/modules/luci-base/htdocs/luci-static/resources/luci.js#L1945-L1958

**Comment by jow-** [comment]
I have no interest in adding additional logic to fix the material theme, the theme should be fixed no not fiddle with the DOM. Where it makes sense we could think about revising the default markup to accommodate for more complex CSS.

**Comment by oldium** [comment]
The `legend` element should be first child of `fieldset` element, but the code does not create any `fieldset`, so it looks like the Material theme is trying to fix the HTML structure actually.

**Comment by jow-** [comment]
Long time ago, section elements used to be `<fieldset>`, nowadays they're `<div>` ones but the legend tag remained as a leftover. I did some cursory googling and it appears `<legend>` is indeed only legal below `<fieldset>` and quirky to style in some situations, which likely is the reason why material tries to replace it.

So `<legend>` should be changed to `<div>` or `<span>` in `form.js` and the legacy templates then.

**Comment by oldium** [comment]
Something like this:

Original:
https://github.com/openwrt/luci/blob/0d0816ca107c84631ab03b5ef2e6d373e102d09a/modules/luci-base/htdocs/luci-static/resources/form.js#L3140-L3141

Changed:
```javascript
 if (typeof(this.title) === 'string' && this.title !== '') 
 	sectionEl.appendChild(E('div', { 'class': 'cbi-section-title' }, this.title));
```
```

**Comment by oldium** [comment]
Other places are trying to render `this.title` as `<h2>` or `<h3>`, which would make sense too.

**Comment by jow-** [comment]
Right, the standard `openwrt`, `bootstrap` and `openwrt2020` themes treat legend equivalent to an h3, so we should use that instead and fix whatever CSS breaks due to this.

**Comment by oldium** [comment]
The Material theme is doing some other DOM tweaks, so the question is whether it actually does anything - especially when views are being loaded asynchronously, so they do not exist when those tweaks are tried to be made.

**Comment by oldium** [comment]
Material theme is not the only one, also Rosy theme is trying to manipulate DOM. Both themes need to be updated to work with client-side rendered views, maybe rendering code of `form.js` could be updated _somehow_ to allow changes by themes.

**Comment by jow-** [comment]
Well, I don't particularly like either theme. Rosy went out of maintenance the moment it got dropped into the tree and Material has these pesky jQuery dependency and ugly DOM manipulations (which Rosy copy-pasted afair).

I prefer to fix the generic markup to be better workable with CSS styling instead of allowing themes to manipulate the DOM. I think that just leads to maintenance hell and incompatibilities.
