### ISSUE TITLE
luci-app-dawn: RPC Error on Network Overview and Hearing Map

### ISSUE THREAD

**Issue by posixPilot** [openwrt/luci#7974]
Hi,

I've installed dawn and luci-app-dawn on OpenWRT 24.10.3.  While the DAWN configuration menu under Network > DAWN works well, the Network Overview and Hearing Map under System > DAWN both throw an RPC error (Error: No related RPC reply) when loaded.

<img width="971" height="295" alt="Image" src="https://github.com/user-attachments/assets/813b1367-5a85-42c3-b6f0-f22f548a72da" />

I cannot find any relevant error messages in the system log.  Dawn appears to be working, as I can see beacon requests and responses in the system log.  I've also verified that rpc-mod-ucode is installed.  Versions of relevant packages below:

root@openwrt-lr:/etc/config# opkg list | egrep "luci |luci-app-dawn|rpc-mod-ucode"
luci - 25.250.61039~923f8d9
luci-app-dawn - 25.273.68624~395e73d
rpcd-mod-luci - 20240305-r1

Any help would be appreciated; I've never used DAWN before so I'm not sure what I should be expecting to see.

  Thanks
  Mike

**Comment by mali7618** [comment]
I am seeing this over here, too. DAWN worked before (incl luci), now, behavior is as described. JSON data returned by openwrt device seems to be corrupt. After some successful responses, there is a response that Firefox considers errorneous ("SyntaxError: JSON.parse: expected property name or '}' at line 1 column 39 of the JSON data"). The begining of that response is:

`[{"jsonrpc":"2.0","id":5,"result":[0,{{"00:04:20:27:85:80":{"30:D3:2D:47:FF:B0":{"signal":-52,"rcpi":-1,"rsni":-1,"freq":2412,"ht_capabilities":false,"vht_capabilities":false,"channel_utilization":76,"num_sta":0,"ht_support":true,"vht_support":false,"score":75},"30:D3:2D:47:FF:B1":{"signal":-52,"rcpi":-1,"rsni":-1,"freq":2412,"ht_capabilities":false,"vht_capabilities":false,"channel_utilization":76,"num_sta":2,"ht_support":true,"vht_support":false,"score":75}, ...`

If I remove that first device, a Logitech Squeezebox Radio, from the network, some other device will show up in first position. I guess it is that first position which will always have not "signal" element, not especially related to that device itself.

**Comment by systemcrash** [comment]
Evidently the produced JSON is incorrectly formatted. Note the "{{" in your JSON.

**Comment by dwmw2** [comment]
Should be fixed by https://github.com/openwrt/iwinfo/pull/29

**Comment by XXOOBOB** [comment]
搞不懂为什么我编译的openwrt报RPC call to luci/getFeatures failed with error -32000: Object not found错误。

**Comment by IgnacioHR** [comment]
Just upgraded OpenWRT on 8 Access Points at home and the issue still persist on 24.10.5

FWI
```
# opkg list-installed | grep iwinfo
iwinfo - 2024.10.20~b94f066e-r1
libiwinfo-data - 2024.10.20~b94f066e-r1
libiwinfo20230701 - 2024.10.20~b94f066e-r1
rpcd-mod-iwinfo - 2025.09.01~bba95191-r1

```

**Comment by systemcrash** [comment]
If someone picks https://github.com/openwrt/iwinfo/pull/29 to openwrt master then the 24 branch should be fixed.

**Comment by edrikk** [comment]
Running snapshot build https://github.com/openwrt/openwrt/commit/caef0a839a80749b7a125f09cb26814980fb7202 which is from 5 days ago (or roughly a week after the above merge), I'm still seeing the "No related RPC reply" error in the DAWN status pages of all routers I've updated (varous mediatek devices, as well as an X86 device).

```
iwinfo	2025.11.07~5f4c213f-r1
libiwinfo-data	2025.11.07~5f4c213f-r1
libiwinfo20230701	2025.11.07~5f4c213f-r1
rpcd-mod-iwinfo	2025.12.03~ffb9961c-r1
```

**Comment by IgnacioHR** [comment]
I dig deeper this morning into the issue and manage to do a workaround. Here are the steps to fix the issue temporarily:

1. Open a terminal to one of the APs and type the command `ubus call dawn get_network`
```
# ubus call dawn get_network
{
	{
		"30:68:93:D1:66:B4": {
			"channel": 6,
			"freq": 2437,
			"channel_utilization": 137,
			"num_sta": 0,
			"ht_support": true,
			"vht_support": false,
			"op_class": 81,
			"local": true,
			"neighbor_report": "306893d169b4ef4900005106070603000600",
			"iface": "phy1-ap0",
			"hostname": "chiton-ap9"
		},
		"30:68:93:D1:66:B5": {
			"channel": 52,
			"freq": 5260,
			"channel_utilization": 18,
			"num_sta": 0,
			"ht_support": true,
			"vht_support": true,
			"op_class": 128,
			"local": true,
...
```
Note the json is broken, but the interesting bit of information is the `hostname` field. It indicates exactly the AP that is generating the error.

2. Open a terminar into the AP indicated in the `hostname` field and:
```
# ssh chiton-ap9
...
# cd /var/run
# vim hostapd-phy?.conf     <-- note, this will edit two files in my case and I've radio 0 and 1, use :n in vim to jump to the second file
```

3.  Search for your ssid and add a new line as follows:
```
...
# Setup interface: phy0-ap0
interface=phy0-ap0
bssid=30:68:93:d1:66:b5
ssid2="chiton"
ssid=chiton     <-- Add this line, without quotes!!!
ctrl_interface=/var/run/hostapd
ap_isolate=1
...
```

4. Restart dawn using `/etc/init.d/dawn restart`

You can repeat command on step 1 until you see a valid json.

Wait some time for all other APs to synchronize values.

The error is gone at the moment the json is valid.

My humble conclusion is that the fix in `iwinfo` is not working as expected because we need `dawn` code to search for `ssid2` when `ssid` is not found. [Searching for ssid2 in the dawn repository](https://github.com/search?q=repo%3Aberlin-open-wireless-lab%2FDAWN%20ssid2&type=code) gives you just one issue but nothing else. I may be wrong so apologies if i'm not right.

**Comment by edrikk** [comment]
As a data point all my APs have "ssid" (and none have ssid2).
The only oddity might be that my x86 devices does not have wireless defined, but I do have hostapd and dawn installed there so that I can see DAWN status on that device.  Wireless is not configured (no wireless menu item).

I dont see any open curly braces "{" without data preceding the 2nd one as stated above.  Is that what you refer to when you say "error" is is that something else in the JSON?

**Comment by dwmw2** [comment]
> iwinfo	2025.11.07~5f4c213f-r1

That's the commit *before* the fix. The date is a bit of a giveaway too. It hasn't made it to an OpenWrt package yet.

**Comment by infirms** [comment]
running: 
OpenWrt 25.12.0-rc1 r32353-9e9b05130c / LuCI openwrt-25.12 branch 25.354.53923~6ce1552

with:
luci-app-dawn 25.357.44569~214ea72

Issue still persists

**Comment by IgnacioHR** [comment]
> I dont see any open curly braces "{" without data preceding the 2nd one as stated above. Is that what you refer to when you say "error" is is that something else in the JSON?

Copy the JSON obtained and use an online JSON validation web page. I don't have DAWN and hosapd installed on my router so I can't test your setup. You can also anonymize your json (change the sensible values and the MAC addresses) and paste it in a reply.

**Comment by IgnacioHR** [comment]
> > iwinfo	2025.11.07~5f4c213f-r1
> 
> That's the commit _before_ the fix. The date is a bit of a giveaway too. It hasn't made it to an OpenWrt package yet.

So, we need to keep waiting. Thank you for your time to implement the fix!

**Comment by ippei-i** [comment]
Until the official fix is ​​released, you can resolve this error by adding the following to your luci local startup:

```
# Fix Dawn stat
sleep 3
sed '/^ssid2="\([^"]*\)"/{h;s//&\nssid=\1/}' /var/run/hostapd-phy0.conf -i
sed '/^ssid2="\([^"]*\)"/{h;s//&\nssid=\1/}' /var/run/hostapd-phy1.conf -i
/etc/init.d/dawn restart
```

**Comment by leandrolnh** [comment]
iwinfo was updated with commit https://github.com/openwrt/openwrt/commit/2139360a781b65045caba3b264c7165dba03ef81
I think this can be closed now.

**Comment by systemcrash** [comment]
https://github.com/openwrt/openwrt/pull/21347

That's in master - but it should be picked to 25.12 also.

**Comment by systemcrash** [comment]
See https://github.com/openwrt/openwrt/pull/21357
