### ISSUE TITLE
for-17.01 branch?

### ISSUE THREAD

**Issue by cshoredaniel** [openwrt/luci#950]
@jow- Is the plan to fork this branch at the same time as the packages branch?  There's a few things that would be 'nice to have' for the release, but they are no release-critical and I hesitate to do hasty commits.

**Comment by cshoredaniel** [comment]
@jow- Seems I missed the fork/freeze announcemnt; should the last few days of PR's I've merged be reverted from for-17.01? (I mean I've tested them, but they've received limited exposure).

**Comment by jow-** [comment]
Leave them in, I guess it is fine. We still have some time left to stabilize things.

**Comment by thess** [comment]
Best to move forward and stabilize a release no need to go backward at this time.

**Comment by cshoredaniel** [comment]
Ok, thanks.
